# Setting up an apex domain for Github pages: https://help.github.com/articles/setting-up-an-apex-domain/
---

aws:
  iam:
    groups:
      administrators:
        roles:
          - AdministratorAccess
      developers:
        roles:
          - PowerUserAccess
      applications:
        roles:
          - PowerUserAccess
    users:
      admin:
        temp_pass: "{{ vault_aws.iam.users.admin.temp_pass }}"
        access_key: "{{ vault_aws.iam.users.admin.access_key }}"
        secret_key: "{{ vault_aws.iam.users.admin.secret_key }}"
        access_key_ids:
          - "{{ vault_aws.iam.users.admin.access_key }}"
        groups:
          - administrators
      production:
        temp_pass: null
        groups:
          - applications
  route53:
    zones:
      opapy.ch: null
    records:
      opapy.ch:
        zone: opapy.ch
        type: A
        ttl: 3600
        value: 192.30.252.153,192.30.252.154
