# Setting up an apex domain for Github pages: https://help.github.com/articles/setting-up-an-apex-domain/
---

aws:
  iam:
    groups:
      administrators:
        roles:
          - AdministratorAccess
      developers:
        roles:
          - PowerUserAccess
      applications:
        roles:
          - PowerUserAccess
    users:
      admin:
        temp_pass: "{{ vault_aws.iam.users.admin.temp_pass }}"
        access_key: "{{ vault_aws.iam.users.admin.access_key }}"
        secret_key: "{{ vault_aws.iam.users.admin.secret_key }}"
        access_key_ids:
          - "{{ vault_aws.iam.users.admin.access_key }}"
        groups:
          - administrators
      production:
        temp_pass: null
        groups:
          - applications
  route53:
    zones:
      opapy.ch: null
    records:
      root:
        zone: opapy.ch
        record: opapy.ch
        type: A
        ttl: 3600
        value: 103.203.90.2
      mail:
        zone: opapy.ch
        record: opapy.ch
        type: MX
        ttl: 3600
        value: 1 aspmx.l.google.com,5 alt1.aspmx.l.google.com,5 alt2.aspmx.l.google.com,10 aspmx2.googlemail.com,10 aspmx3.googlemail.com
      spf:
        zone: opapy.ch
        record: opapy.ch
        type: SPF
        ttl: 3600
        value: "\"v=spf1 include:_spf.google.com ~all\""
      txt:
        zone: opapy.ch
        record: kloudsecverify2472.opapy.ch
        type: TXT
        ttl: 3600
        value: "\"UezDeJwzJCbVWHhsxivwuM5V\""
